In [1]:
import pandas as pd
import numpy as np
import time  
from sklearn import metrics  
import pickle as pickle  
from sklearn.cross_validation import train_test_split 

C:\Users\chenyuxiang\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [4]:
def read_data(data_file_path):  
    
    training_df = pd.read_csv(data_file_path, header=0)
    feature_cols = ['T0101','T0102','T0201','T0202','T0203','T0204','T0205','T0206','T0207','T0208','T0209','T0210','T0211','T0212','T0213',
'T0301','T0302','T0303','T0304','T0305','T0306','T0307','T0308','T0309']
    x = training_df[feature_cols]
    y = training_df['LEGAL_RECORD']
    x_train,x_test, y_train, y_test = train_test_split(x, y, random_state=1) 
    
    return training_df, x_train, y_train, x_test, y_test

In [5]:
data_file = "C:/Users/chenyuxiang/Desktop/Legal_Illegal_Record_all_data.csv"  

all_data_df, train_x, train_y, test_x, test_y = read_data(data_file)

In [6]:
# Multinomial Naive Bayes Classifier  
def naive_bayes_classifier(train_x, train_y):  
    from sklearn.naive_bayes import MultinomialNB  
    model = MultinomialNB(alpha=0.01)  
    model.fit(train_x, train_y)  
    return model 

In [7]:
NB_model = naive_bayes_classifier(train_x, train_y)

In [8]:
predict_y_array = NB_model.predict(test_x)

In [12]:
predict_y = pd.DataFrame({'Legal_Predict': predict_y_array})
predict_y.index = test_y.index

test_y_df = test_y.to_frame()

In [13]:
result_y_df = pd.merge(predict_y, test_y_df, left_index=True, right_index=True)

In [14]:
result_df = pd.merge(result_y_df, test_x, left_index=True, right_index=True)

In [15]:
predict_incorrect_df = result_df[result_df['Legal_Predict'] != result_df['LEGAL_RECORD']]

In [16]:
all_data_result_df = pd.merge(predict_y, all_data_df, left_index = True, right_index = True)

In [17]:
all_data_predict_incorrect_df = all_data_result_df[all_data_result_df['Legal_Predict'] != all_data_result_df['LEGAL_RECORD']]

In [18]:
all_data_predict_incorrect_df

Legal_Predict TRANSPARENCY_LEVEL LEGAL_RECORD  \
190819          Legal                mid      Illegal   
817300          Legal                mid      Illegal   
31998           Legal                mid      Illegal   
1007289         Legal                mid      Illegal   
287235          Legal                low      Illegal   
84568           Legal                mid      Illegal   
196935          Legal                mid      Illegal   
242540          Legal                mid      Illegal   
432758          Legal               high      Illegal   
185060          Legal                mid      Illegal   
903063          Legal                low      Illegal   
315424          Legal                mid      Illegal   
1013991         Legal                mid      Illegal   
1082398         Legal                mid      Illegal   
175689          Legal                mid      Illegal   
951649          Legal                mid      Illegal   
530229          Legal               high      Illegal   
494756          Legal               high      Illegal   
799917          Legal                mid      Illegal   
586452          Legal                mid      Illegal   
195690          Legal                mid      Illegal   
848208          Legal                mid      Illegal   
570506          Legal                mid      Illegal   
484499          Legal                mid      Illegal   
1145996         Legal               high      Illegal   
350031          Legal                mid      Illegal   
479048          Legal                mid      Illegal   
15244           Legal                mid      Illegal   
1010507         Legal                mid      Illegal   
97637           Legal                mid      Illegal   
...               ...                ...          ...   
255114          Legal                mid      Illegal   
31794           Legal                mid      Illegal   
345584          Legal                mid      Illegal   
366277          Legal                mid      Illegal   
1112996         Legal                mid      Illegal   
701178          Legal                mid      Illegal   
552116          Legal                mid      Illegal   
573054          Legal                mid      Illegal   
247482          Legal                mid      Illegal   
30525           Legal                mid      Illegal   
98666           Legal                mid      Illegal   
54171           Legal                mid      Illegal   
518733          Legal                mid      Illegal   
519007          Legal                mid      Illegal   
585080          Legal                mid      Illegal   
1144053         Legal                mid      Illegal   
517041          Legal                low      Illegal   
362637          Legal                mid      Illegal   
25130           Legal                mid      Illegal   
426714          Legal                mid      Illegal   
28488           Legal                mid      Illegal   
349604          Legal                mid      Illegal   
1041284         Legal                mid      Illegal   
545866          Legal                mid      Illegal   
5290            Legal                mid      Illegal   
7255            Legal                mid      Illegal   
262450          Legal                mid      Illegal   
1051470         Legal                mid      Illegal   
672952          Legal                mid      Illegal   
165133          Legal                mid      Illegal   

                           PRIPID     T0101  T0102  T0201     T0202     T0203  \
190819   511025000012014102900445  0.766259    0.0    1.0  1.000000  1.000000   
817300   511681000012016041301586  0.759965    0.0    1.0  1.000000  1.000000   
31998    510781000012016040100778  0.766259    0.0    1.0  1.000000  1.000000   
1007289  510400000012015113000004  0.779196    0.0    1.0  1.000000  1.000000   
287235   511124000012010082700001  0.506643    0.0    0.0  0.000000 

In [26]:
np.exp(NB_model.feature_log_prob_)

array([[4.71212824e-02, 6.20398229e-04, 6.01091379e-02, 5.95947532e-02,
        5.15469430e-02, 6.02562893e-02, 4.51261663e-02, 5.58770837e-02,
        6.19106079e-02, 6.17574132e-02, 5.17003598e-02, 6.19106079e-02,
        6.19106079e-02, 4.84348036e-02, 6.05004161e-02, 3.10831259e-02,
        5.68893288e-02, 6.02148480e-02, 2.87208106e-08, 1.03423639e-04,
        9.96640847e-04, 2.32667286e-04, 3.50422610e-04, 6.17526435e-02],
       [4.61459031e-02, 9.81189214e-04, 5.77068742e-02, 5.72895004e-02,
        4.88091344e-02, 5.77933443e-02, 4.95867032e-02, 5.78897419e-02,
        5.98993351e-02, 5.98248149e-02, 5.59389594e-02, 5.98993351e-02,
        5.98987133e-02, 5.94934456e-02, 5.88813298e-02, 3.51702698e-02,
        5.50924742e-02, 5.84582067e-02, 6.90875662e-10, 3.40256954e-04,
        8.42799910e-04, 6.90875662e-10, 1.95311240e-04, 5.98623560e-02]])

In [25]:
NB_model.coef_

array([[ -3.0759471 ,  -6.92674524,  -2.85237897,  -2.85963791,
         -3.0198378 ,  -2.85088166,  -3.00403256,  -2.84921508,
         -2.81508987,  -2.81633474,  -2.88349419,  -2.81508987,
         -2.81510026,  -2.82188913,  -2.83223122,  -3.34755416,
         -2.89874216,  -2.83944319, -21.09306125,  -7.98580948,
         -7.07878098, -21.09306125,  -8.54091617,  -2.81570742]])

In [23]:
np.exp(NB_model.class_log_prior_)

array([0.02425942, 0.97574058])

In [28]:
all_data_predict_incorrect_df.to_csv('C:/Users/chenyuxiang/Desktop/Legal_Illegal_NB_Incorrect_all.csv')

In [29]:
all_data_result_df.to_csv('C:/Users/chenyuxiang/Desktop/Legal_Illegal_NB_test_all.csv')